Public Enum CodigodeFolios
    EntradaCanalesAlmacen = 4
    EntradaCortesAlmacén = 7
    Registrodeembarques = 9
    RecepcionGanadoPie = 10
    CompradeGanado = 12
    MovimientosdeAlmacen = 13
    SalidasdeReciba = 14
    SalidasdeCorrales = 15
    RecepcionOrdenCompra = 16
    SolicitudServicios = 17
    ComprasDirectas = 18
    CalculodeNomina = 19
    Devoluciones = 20
    TransferenciasAlmacenesProduccion = 21
    MovimientoGanado = 22
    TransferenciaAlmacenGeneralSalida = 23
    TransferenciaAlmacenGeneralEntrada = 24
    PreparacionMezcla = 25
    RecepcionConsignacion = 26
    AplicacionFormula = 27
    AplicacionMedicamento = 28
    ProrrateoMedicamento = 29
    FacturasVentasyCorrales = 30
    PagoEfectivoRecepcionCompra = 31
End Enum